######################################################################
# Automatically generated by qmake (2.01a) Thu May 16 08:02:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CNurikabe.h CQNurikabe.h Puzzles.h help.xpm
SOURCES += CNurikabe.cpp CQNurikabe.cpp
